"""Add communication preferences to User

Revision ID: 4550f4b842fc
Revises: 49668258d314
Create Date: 2025-12-15 12:25:30.642273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4550f4b842fc'
down_revision = '49668258d314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('communication_preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('communication_preferences')

    # ### end Alembic commands ###
