"""add missing tables including messages

Revision ID: 465aa6ec1eef
Revises: 0b3117ce2547
Create Date: 2025-12-25 20:55:15.060088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '465aa6ec1eef'
down_revision = '0b3117ce2547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('companies')
    op.drop_table('system_settings')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_constraint('activity_logs_company_id_fkey', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_branches_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('drawdown_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_drawdown_accounts_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint('fk_groups_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('loan_products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_loan_products_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('loan_types', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_constraint('fk_loan_types_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_loans_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_members_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_categories_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('savings_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_savings_accounts_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_suppliers_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_company_id_fkey', type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_company_id_fkey', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_transactions_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_suppliers_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('savings_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_savings_accounts_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_product_categories_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_members_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_loans_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('loan_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_loan_types_company_id', 'companies', ['company_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('loan_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_loan_products_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_groups_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('drawdown_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_drawdown_accounts_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_branches_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('activity_logs_company_id_fkey', 'companies', ['company_id'], ['id'])

    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_settings_pkey'),
    sa.UniqueConstraint('key', name='system_settings_key_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('subscription_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='companies_pkey'),
    sa.UniqueConstraint('email', name='companies_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name='companies_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('messages')
    # ### end Alembic commands ###
