"""Add grace period and penalty to LoanType

Revision ID: 49668258d314
Revises: bace42f9fe0f
Create Date: 2025-12-15 12:19:35.165036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49668258d314'
down_revision = 'bace42f9fe0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grace_period_days', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('penalty_rate', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rejected_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_loans_rejected_by_users', 'users', ['rejected_by'], ['id'])

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('risk_category', sa.Text(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Text(), nullable=False, server_default='confirmed'))
        batch_op.add_column(sa.Column('confirmed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_transactions_confirmed_by_users', 'users', ['confirmed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('confirmed_by')
        batch_op.drop_column('status')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('risk_category')
        batch_op.drop_column('risk_score')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rejected_date')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('rejected_by')

    with op.batch_alter_table('loan_types', schema=None) as batch_op:
        batch_op.drop_column('penalty_rate')
        batch_op.drop_column('grace_period_days')
    # ### end Alembic commands ###
